/* automatically generated by rust-bindgen 0.69.2 */

extern "C" {
    #[link_name = "inc__extern"]
    pub fn inc(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "dec__extern"]
    pub fn dec(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn hello(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
